artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  zip_file_path: data/PodcastTime.zip
  unzip_dir: artifacts/data_ingestion

data_validation:
  root_dir: artifacts/data_validation
  unzip_data_path: artifacts\data_ingestion\podcast_dataset.csv
  schema_file_path: schema.yaml
  report_file_path: artifacts/data_validation/report.yaml

data_transformation:
  root_dir: artifacts/data_transformation
  data_path: artifacts/data_ingestion/podcast_dataset.csv

model_training:
  root_dir: artifacts/model_training
  train_data_path: artifacts\data_transformation\train.csv
  test_data_path: artifacts\data_transformation\test.csv
  model_path: artifacts/model_training/model.h5

model_evaluation:
  root_dir: artifacts/model_evaluation
  test_data_path: artifacts/data_transformation/test.csv
  model_path: artifacts/model_training/model.h5
  metric_file_path: artifacts/model_evaluation/metrics.json
  target_column: str